/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ManageSharingRouteImport } from './routes/manage-sharing'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as SandboxesIndexRouteImport } from './routes/sandboxes/index'
import { Route as HarnessesIndexRouteImport } from './routes/harnesses/index'
import { Route as CredentialsIndexRouteImport } from './routes/credentials/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as ShareHarnessTokenRouteImport } from './routes/share-harness/$token'
import { Route as SandboxesCreate_sandboxRouteImport } from './routes/sandboxes/create_sandbox'
import { Route as SandboxesSandboxIdRouteImport } from './routes/sandboxes/$sandboxId'
import { Route as HarnessesHarnessIdRouteImport } from './routes/harnesses/$harnessId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSharingRoute = ManageSharingRouteImport.update({
  id: '/manage-sharing',
  path: '/manage-sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxesIndexRoute = SandboxesIndexRouteImport.update({
  id: '/sandboxes/',
  path: '/sandboxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const HarnessesIndexRoute = HarnessesIndexRouteImport.update({
  id: '/harnesses/',
  path: '/harnesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsIndexRoute = CredentialsIndexRouteImport.update({
  id: '/credentials/',
  path: '/credentials/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareHarnessTokenRoute = ShareHarnessTokenRouteImport.update({
  id: '/share-harness/$token',
  path: '/share-harness/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxesCreate_sandboxRoute = SandboxesCreate_sandboxRouteImport.update({
  id: '/sandboxes/create_sandbox',
  path: '/sandboxes/create_sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxesSandboxIdRoute = SandboxesSandboxIdRouteImport.update({
  id: '/sandboxes/$sandboxId',
  path: '/sandboxes/$sandboxId',
  getParentRoute: () => rootRouteImport,
} as any)
const HarnessesHarnessIdRoute = HarnessesHarnessIdRouteImport.update({
  id: '/harnesses/$harnessId',
  path: '/harnesses/$harnessId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/manage-sharing': typeof ManageSharingRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/harnesses/$harnessId': typeof HarnessesHarnessIdRoute
  '/sandboxes/$sandboxId': typeof SandboxesSandboxIdRoute
  '/sandboxes/create_sandbox': typeof SandboxesCreate_sandboxRoute
  '/share-harness/$token': typeof ShareHarnessTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/chat/': typeof ChatIndexRoute
  '/credentials/': typeof CredentialsIndexRoute
  '/harnesses/': typeof HarnessesIndexRoute
  '/sandboxes/': typeof SandboxesIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/manage-sharing': typeof ManageSharingRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/harnesses/$harnessId': typeof HarnessesHarnessIdRoute
  '/sandboxes/$sandboxId': typeof SandboxesSandboxIdRoute
  '/sandboxes/create_sandbox': typeof SandboxesCreate_sandboxRoute
  '/share-harness/$token': typeof ShareHarnessTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/chat': typeof ChatIndexRoute
  '/credentials': typeof CredentialsIndexRoute
  '/harnesses': typeof HarnessesIndexRoute
  '/sandboxes': typeof SandboxesIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/manage-sharing': typeof ManageSharingRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/harnesses/$harnessId': typeof HarnessesHarnessIdRoute
  '/sandboxes/$sandboxId': typeof SandboxesSandboxIdRoute
  '/sandboxes/create_sandbox': typeof SandboxesCreate_sandboxRoute
  '/share-harness/$token': typeof ShareHarnessTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/chat/': typeof ChatIndexRoute
  '/credentials/': typeof CredentialsIndexRoute
  '/harnesses/': typeof HarnessesIndexRoute
  '/sandboxes/': typeof SandboxesIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/manage-sharing'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/harnesses/$harnessId'
    | '/sandboxes/$sandboxId'
    | '/sandboxes/create_sandbox'
    | '/share-harness/$token'
    | '/share/$token'
    | '/chat/'
    | '/credentials/'
    | '/harnesses/'
    | '/sandboxes/'
    | '/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/manage-sharing'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/harnesses/$harnessId'
    | '/sandboxes/$sandboxId'
    | '/sandboxes/create_sandbox'
    | '/share-harness/$token'
    | '/share/$token'
    | '/chat'
    | '/credentials'
    | '/harnesses'
    | '/sandboxes'
    | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/manage-sharing'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/harnesses/$harnessId'
    | '/sandboxes/$sandboxId'
    | '/sandboxes/create_sandbox'
    | '/share-harness/$token'
    | '/share/$token'
    | '/chat/'
    | '/credentials/'
    | '/harnesses/'
    | '/sandboxes/'
    | '/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ManageSharingRoute: typeof ManageSharingRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  HarnessesHarnessIdRoute: typeof HarnessesHarnessIdRoute
  SandboxesSandboxIdRoute: typeof SandboxesSandboxIdRoute
  SandboxesCreate_sandboxRoute: typeof SandboxesCreate_sandboxRoute
  ShareHarnessTokenRoute: typeof ShareHarnessTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ChatIndexRoute: typeof ChatIndexRoute
  CredentialsIndexRoute: typeof CredentialsIndexRoute
  HarnessesIndexRoute: typeof HarnessesIndexRoute
  SandboxesIndexRoute: typeof SandboxesIndexRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-sharing': {
      id: '/manage-sharing'
      path: '/manage-sharing'
      fullPath: '/manage-sharing'
      preLoaderRoute: typeof ManageSharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandboxes/': {
      id: '/sandboxes/'
      path: '/sandboxes'
      fullPath: '/sandboxes/'
      preLoaderRoute: typeof SandboxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harnesses/': {
      id: '/harnesses/'
      path: '/harnesses'
      fullPath: '/harnesses/'
      preLoaderRoute: typeof HarnessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials/': {
      id: '/credentials/'
      path: '/credentials'
      fullPath: '/credentials/'
      preLoaderRoute: typeof CredentialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-harness/$token': {
      id: '/share-harness/$token'
      path: '/share-harness/$token'
      fullPath: '/share-harness/$token'
      preLoaderRoute: typeof ShareHarnessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandboxes/create_sandbox': {
      id: '/sandboxes/create_sandbox'
      path: '/sandboxes/create_sandbox'
      fullPath: '/sandboxes/create_sandbox'
      preLoaderRoute: typeof SandboxesCreate_sandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandboxes/$sandboxId': {
      id: '/sandboxes/$sandboxId'
      path: '/sandboxes/$sandboxId'
      fullPath: '/sandboxes/$sandboxId'
      preLoaderRoute: typeof SandboxesSandboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harnesses/$harnessId': {
      id: '/harnesses/$harnessId'
      path: '/harnesses/$harnessId'
      fullPath: '/harnesses/$harnessId'
      preLoaderRoute: typeof HarnessesHarnessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ManageSharingRoute: ManageSharingRoute,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  HarnessesHarnessIdRoute: HarnessesHarnessIdRoute,
  SandboxesSandboxIdRoute: SandboxesSandboxIdRoute,
  SandboxesCreate_sandboxRoute: SandboxesCreate_sandboxRoute,
  ShareHarnessTokenRoute: ShareHarnessTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  ChatIndexRoute: ChatIndexRoute,
  CredentialsIndexRoute: CredentialsIndexRoute,
  HarnessesIndexRoute: HarnessesIndexRoute,
  SandboxesIndexRoute: SandboxesIndexRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
